### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by panda6412** [kb47/pdf-poppler#7]
{ Error: spawn C:\Users\USER\Desktop\project\print-helper-server\app\lib\win\poppler-0.51\bin\pdftocairo ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at Object.<anonymous> (C:\Users\USER\Desktop\project\print-helper-server\node_modules\@babel\node\lib\_babel-node.js:234:23)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)  errno: 'ENOENT',
  code: 'ENOENT',
  syscall:
   'spawn C:\\Users\\USER\\Desktop\\project\\print-helper-server\\app\\lib\\win\\poppler-0.51\\bin\\pdftocairo',
  path:
   'C:\\Users\\USER\\Desktop\\project\\print-helper-server\\app\\lib\\win\\poppler-0.51\\bin\\pdftocairo',
  spawnargs:
   [ [ '-png' ],
     [ '-scale-to' ],
     [ 1024 ],
     'C:\\Users\\USER\\Desktop\\project\\print-helper-server\\dummy_files\\B6_Waybill_V.pdf',
     'B6_Waybill_V.pdf\\C:\\Users\\USER\\Desktop\\project\\print-helper-server\\dummy_files' ],
  cmd:
   'C:\\Users\\USER\\Desktop\\project\\print-helper-server\\app\\lib\\win\\poppler-0.51\\bin\\pdftocairo -png -scale-to 1024 C:\\Users\\USER\\Desktop\\project\\print-helper-server\\dummy_files\\B6_Waybill_V.pdf B6_Waybill_V.pdf\\C:\\Users\\USER\\Desktop\\project\\print-helper-server\\dummy_files' }

**Comment by pavsmk** [comment]
try to install or update poppler on your system

**Comment by elm2013** [comment]
> try to install or update poppler on your system

I installed it, but get  Error: spawn ./usr/bin/pdftocairo ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
